// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgdsdryldqcrpcabysnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnZHNkcnlsZHFjcnBjYWJ5c25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0OTc3NDIsImV4cCI6MjA2OTA3Mzc0Mn0.nTbYfmH9olGRF6jMSZHEe31j-XGN0YojmYBe9S_0IIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});